  let nextLink="";let nb2="";let gonzu="";let gonzu2="";let ga=$('#chatBox');   let ga98=$('.gazoulod'); var remo= function(){$('.gazoulod').remove();}
                 const openBtn=document.getElementById("openChatBtn");const chatPopup=document.getElementById("chatPopup");const closeBtn=document.getElementById("closeChatBtn");const chatBox=document.getElementById("chatBox");const inputField=document.getElementById("chatInput");let isSending = false; const button = document.getElementById("sendBtn");
inputField.addEventListener("keydown", function(e) {  if (e.key === "Enter" && !isSending) {    isSending = true;      button.click();
    setTimeout(() => {      isSending = false;    }, 1000);  }});             
 var gg2= function(){  function fetchAllPages(keyword, pageUrl, collected, maxPages){  pageUrl =nextLink;    collected = collected || [];
    maxPages = maxPages || 5;
 $.ajax({      url: pageUrl,      type: 'GET',      dataType: 'html',      success: function(html){        const doc = $('<div>').html(html);
 doc.find('#list .list-item').each(function(){          collected.push({            title: $(this).find(".list-item-titlezz a").text(),            link: $(this).find(".x-top-post78").attr('href'),            text77: $(this).find(".bla-top-a2").text()            });  });
  nextLink = doc.find(".blog-pager-older7g").text(); nb2=nextLink.length;           console.log('取得完了', collected.length, '件');          showResults(collected);
 },      error: function(xhr){  remo();   console.log('取得エラー:', xhr.status);  }}); }
  function showResults(data){const count = data.length;
 if(nb2 > 5){ const html =  data.map(p =>
      `<div class="link-all-ct"><a href="${p.link}" target="_blank" class="aftehurr aftehurr55">${p.title}</a><p class="tenbebe">${p.text77}</p></div>`
    ).join(''); ga.append(`<div class="message bot"><span>`+html+`</span></div><div class="message bot"><button id="moreBtn">もっと取得する</button></div>`);}    else{   const html = `${count} 件 ${nextLink}` + data.map(p =>
      `<div class="link-all-ct"><a href="${p.link}" target="_blank" class="aftehurr aftehurr55">${p.title}</a><p class="tenbebe">${p.text77}</p></div>`
    ).join(''); remo();  ga.append('<div class="message bot"><span>'+html+'</span></div>');} }
fetchAllPages();  };
                 
 var gg1= function(){const papa=nextLink.length;
  function fetchAllPages(keyword, pageUrl, collected, maxPages){   if(papa > 5){  pageUrl = nextLink;}else{pageUrl = 'https://www.net-frx.com/search?q='+gonzu;}
    collected = collected || [];    maxPages = maxPages || 5;
  $.ajax({      url: pageUrl,      type: 'GET',      dataType: 'html',      success: function(html){        const doc = $('<div>').html(html);
        doc.find('#list .list-item').each(function(){          collected.push({            title: $(this).find(".list-item-titlezz a").text(),
            link: $(this).find(".x-top-post78").attr('href'),            text77: $(this).find(".bla-top-a2").text()            }); });
 nextLink = doc.find(".blog-pager-older7g").text(); nb2=nextLink.length; 
          console.log('取得完了', collected.length, '件');
          showResults(collected);  },      error: function(xhr){  remo(); ga.append('<div class="message bot"><span>エラーです🤔<br/>検索ワードを変えて試してみて下さい。</span></div>');      }    });  }
  function showResults(data){const count = data.length;const dao=data.length;if(dao==0){ remo(); ga.append('<div class="message bot"><span>0件です🤔<br/>検索ワードを変えて試してみて下さい👏</span></div>'); }else{    const html = data.map(p =>
      `<a href="${p.link}" target="_blank" class="aftehurr aftehurr55">${p.title}</a><p class="tenbebe">${p.text77}</p>`
    ).join('');                if(nb2 > 5){ gg2();}  remo();   ga.append('<div class="message bot"><span>'+html+'</span></div>');} }
fetchAllPages(); };

   let nu0="";const nu1="%20";const nu2="%20OR%20";nu0=nu1;
 document.getElementById("sendBtn").addEventListener("click", function() {let jaa="";nextLink="";
  gonzu= document.getElementById("chatInput").value;ga.append('<div class="message user"><span>'+gonzu+'</span></div>'); ga.append('<img class="gazoulod" src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgeegZPlfPTbOHtNhQLnXKoHtq40iy1p9bS4Z8rvgiKk-tRYT1DfeoXgJpivVrDwhC9z31DuE3Ha_JSiH4QD3lXGCV-v91x0LKlot4nAML7F_hqQOj6gm0veyvWwx2ft1UZDfZ6DROPdCxOhtfRMQ-QxLd2Sd9NfwzdTCYIGKGFr87nvOZRE0SL3y3StnU/s1600-rw-e30/loading-7712_128.webp" />');  chatBox.scrollTop = chatBox.scrollHeight + 50;
    const mi=gonzu.toLowerCase();
    if (gonzu.includes("配信") && gonzu.includes("終了")) {setTimeout(function() {ga.append(`<div class="message bot"><span>💡 Netflixの配信終了作品は以下のページでご確認ください。<br/><br/>✅ 配信終了作品<br/><a href="https://www.net-frx.com/p/netflix-expiring.html" target="_blank" rel="noopener noreferrer" class="aftehurr345">https://www.net-frx.com/p/netflix-expiring.html</a><br/><br/>✅ 過去の配信終了作品<br/><a href="https://www.net-frx.com/p/netflix-leaved-all.html" target="_blank" rel="noopener noreferrer" class="aftehurr345">https://www.net-frx.com/p/netflix-leaved-all.html</a></span></div>`);}, 2000);}else if (gonzu.includes("配信予定")) {setTimeout(function() {ga.append(`<div class="message bot"><span>✅ Netflix配信予定掲載ページ<br/><a href="https://www.net-frx.com/p/netflix-coming-soon.html" target="_blank" rel="noopener noreferrer" class="aftehurr345">https://www.net-frx.com/p/netflix-coming-soon.html</a><br /><br/>✅ Netflix全新着作品ページ<br/><a href="https://www.net-frx.com/search?&max-results=20" target="_blank" rel="noopener noreferrer" class="aftehurr345">https://www.net-frx.com/search</a></span></div>`);}, 2000);}else if (mi.includes("モード")) {
 
     if (mi.includes("or")) {nu0=nu2;ga.append('<div class="message bot"><span>✅ 検索モードを <b>or</b> に切り替えました。</span></div>');} else if (mi.includes("and")){ nu0=nu1;ga.append('<div class="message bot"><span>✅ 検索モードを <b>and</b> に切り替えました。</span></div>');}else{ga.append('<div class="message bot"><span>⚠️ モードは「and」または「or」で指定してください。</span></div>');}}else if (gonzu.includes("おすすめ") || gonzu.includes("オススメ") || gonzu.includes("面白い") || gonzu.includes("お勧め")) {setTimeout(function() {ga.append(`<div class="message bot"><span>💡 Netflixで配信中のオススメ作品を検索する場合は「高い評価」「大ヒット」のキーワードを入力するのがオススメです👍<br/><br/>例：「<i class="jpacheck790">海外映画 高い評価</i>」「<i class="jpacheck790">海外TV 高い評価</i>」「<i class="jpacheck790">海外 大ヒット</i>」「<i class="jpacheck790">国内 大ヒット</i>」<br/><br/>💡国内作品は映画だと「キネマ旬報」、アニメだと「このマンガがすごい」もオススメです👍<br/><br/>例：「<i class="jpacheck790">国内映画 キネマ旬報</i>」「<i class="jpacheck790">アニメ このマンガがすごい</i>」</span></div>`);}, 2000);}else if (gonzu.includes("吹替") || gonzu.includes("吹き替え")) {setTimeout(function() {ga.append(`<div class="message bot"><span>💡 日本語吹き替え対応作品を検索する場合は「JPA」のキーワードをご使用ください。<br/><br/>例：「<i class="jpacheck790">海外映画 JPA</i>」「<i class="jpacheck790">海外TV JPA</i>」「<i class="jpacheck790">アニメ JPA</i>」</span></div>`);}, 2000);}else if (gonzu.includes("新着")) {setTimeout(function() {ga.append(`<div class="message bot"><span>✅ Netflix新着作品掲載ページ(新着順)<br/><a href="https://www.net-frx.com/search?&max-results=20" target="_blank" rel="noopener noreferrer" class="aftehurr345">https://www.net-frx.com/search</a></span></div>`);}, 2000);}else if (mi.includes("get") && mi.includes("freax") || mi.includes("freax")) {setTimeout(function() {ga.append(`<div class="message bot"><span>💡 当サイト『Get FreaX』はNetflixの非公式ファンサイトです。<br/><br/>Netflixの新着作品、配信予定、配信終了予定、日本語吹き替え対応作品などを紹介していますよ👍<br/>Netflix以外のVOD総合情報も掲載中です😄<br/><br/>✅ Netflix新着作品掲載ページ<br/><a href="https://www.net-frx.com/search?&max-results=20" target="_blank" rel="noopener noreferrer" class="aftehurr345">https://www.net-frx.com/search</a><br/><br/>✅ Netflix配信予定掲載ページ<br/><a href="https://www.net-frx.com/p/netflix-coming-soon.html" target="_blank" rel="noopener noreferrer" class="aftehurr345">https://www.net-frx.com/p/netflix-coming-soon.html</a><br/><br/>✅ Netflix配信終了予定掲載ページ<br/><a href="https://www.net-frx.com/p/netflix-expiring.html" target="_blank" rel="noopener noreferrer" class="aftehurr345">https://www.net-frx.com/p/netflix-expiring.html</a><br/><br/>✅ VOD総合情報掲載ページ<br/><a href="https://www.net-frx.com/p/video-on-demand-information.html" target="_blank" rel="noopener noreferrer" class="aftehurr345">https://www.net-frx.com/p/video-on-demand-information.html</a></span></div>`);}, 2000);}else{ 
//  ga.append('<div class="message bot"><span>⏳ 作品を検索中です...</span></div>'); 
gonzu=gonzu.replace(/ /g, nu0).replace(/　/g, nu0).replace(/日本/g, "国内");     
      if (mi.includes("海外") && mi.includes("tv")) {jaa='<br/>💡 海外TVドラマライナップ一覧は以下のページでもご確認できます。<br/><p class="sentanko88"><a href="https://www.net-frx.com/p/netflix-drama-line-up.html" target="_blank" rel="noopener noreferrer" class="aftehurr345">https://www.net-frx.com/p/netflix-drama-line-up.html</a></p>'}
      
      ga.append('<div class="message bot"><span><p class="sentanko88">📝Get Freax 検索ワード一覧URL<br/><a href="https://www.net-frx.com/search?q='+gonzu+'&max-results=20" target="_blank" rel="noopener noreferrer" class="aftehurr345">https://www.net-frx.com/search?q='+gonzu+'</a></p>'+jaa+'</span></div>');
 gg1();} remo(); chatBox.scrollTop = chatBox.scrollHeight + 50;  });
 $(document).on('click', '#moreBtn', function(){ $(this).hide();gg1(); });
      $(document).on('click', '.jpacheck790', function(){ const nb=$(this).text();$("#chatInput").val(nb); });  
 $(document).on('click', '#closeChatBtn, .sabu777, .sabu777ob', function(e){ const id = e.target.id; if (id !== "chatBox" && id !== "chatInput" && id !== "inputContainer" && id !== "sendBtn") {  const zazmm7 = $('#chatPopup,.sabu777, .sabu777ob, #inputField'); zazmm7.fadeOut(50);   $('body').removeClass('sccansell'); $(".menu-dbb1, #ad-bottom-f1ads, #ad-bottom-pc0").fadeIn(200);  } });  
