 $(document).on('click', '.info-post-list-sec', function () {$(this).parent().parent().parent().find(".info-line-tab-TP").click();}); $(document).one('click', '.info-line-tab-TP, #all-class-bt', function () {               $(function(){ var d = document;		var link = d.createElement('link');		link.href = 'https://cdnjs.cloudflare.com/ajax/libs/lity/1.6.6/lity.css';		link.rel = 'stylesheet';		link.type = 'text/css';		var h = d.getElementsByTagName('head')[0];		h.appendChild(link); $.getScript("https://cdnjs.cloudflare.com/ajax/libs/lity/1.6.6/lity.js"); }); });
   $(document).on('click', '.info-line-tab-TP, #all-class-bt', function () {   $('body').addClass('sccansell');$(".menu-dbb3, .menu-dbb1, #ad-bottom-f1ads,#ad-bottom-pc0, .ad-sticky2").hide();$(".pofuk55").show();    const tap99 = $(this).parent().find(".list-item-img-xx").attr('src');  const tap = $(this).parent().find("#getreview7").text();const tap5 = $(this).parent().find(".list-item-titlezz a").text(); $(".popu2-ch2b1xx-cc").append("<div class='huupo65 tag-huupo65vc'>"+tap+"</div>"); const fx29 = $(this).parent().find(".list-item-img-xx").attr('src'); $(".top-sch-01").css('background-image', 'url(' + fx29 + ')');                const gui = $(this).parents().attr("class");    $(".sabu777dr, .acten-on1dr, .acten-on2dr").fadeIn(200);  $("<span class='get-titlebnb'>"+tap5+"</span>").appendTo('.acten-1dr, #titelt-cobet1');let gclas=$(this).attr("class"); if(gclas.indexOf("comet-kont-rv") >= 0){$(".hideonly-tw").addClass("dspp10");let voncomen2 = function(){$(".rev-ck-po00").click();  } ;setTimeout(voncomen2, 100); $(".pofuk55").hide(); $(".acten-1dr-nn55, .popu2-ch-net2, .popu2-ch25b, .top-sch-01, .popu2-ch2b1-c, .popu2-ch2b1xx-cc, .acten-on2dr-in").show();}else{$(".hideonly-tw").removeClass("dspp10"); $(function(){      $.ajax({   type: 'GET',        url: tap,        dataType: 'html',        success: function(data) {           const blbl = $(data).find(".post-body blockquote").text(); $(".top-sch-03").append(blbl);  const cnt = $(data).find(".post-body .date-count").text();        const nend=$(data).find(".post-body .mosmos a").attr('href');$(".popu2-ch-net2 a").attr('href',nend);    const nend5=$(data).find(".post-body .post_fffm").text();  if(nend5.indexOf("JPA")  >= 0) {$(".list-sub-aud10").show();}    
   const gamp5=$(data).find(".post-body .rate-box .imdbRatingPlugin").data("title"); const gaa =JSON.stringify(gamp5);   const gamp52=gaa.length;   if(gamp52 >3){  const settings = {		"async": true,	"crossDomain": true,	"url": "https://moviesdatabase.p.rapidapi.com/titles/"+gamp5+"/ratings",		"method": "GET",
	"headers": {		"X-RapidAPI-Key": "22eca568b9msh804a6ec15bb9372p1cd153jsn4e1656e041e2",		"X-RapidAPI-Host": "moviesdatabase.p.rapidapi.com"	}               };       $.ajax(settings).done(function (response) { const ra =JSON.stringify(response);    const ra3= new Object(response["results"]);   const ra7 =ra3["averageRating"];     const ra5 =JSON.stringify(ra7);       const bv55b = $(".list-sub-lg1b");bv55b.show();bv55b.find("div").append("<span class='imdb-po56'>"+ra5+"</span>");$(".list-sub-lg2b").show(); });}
 const deg7 = $(data).find(".post-body #tv55dtt").data("tvdd");    const re2 = $(data).find(".post-body .tmzzz55").attr('id');
 const ipp = $(data).find(".post-body .rate-box .imdbRatingPlugin").data("title");  const ipp2=ipp.length;                                                                      
 $(function(){       if(ipp2 > 5){const bv55 = $(".popu2-ch2b1-c");bv55.append("<div class='penimdb'><a href='https://www.imdb.com/title/"+ipp+"' rel='noopener noreferrer' target='_blank'>IMDb <i class='im-external-link-alt'/></a></div>");setTimeout(function(){ $(".popu2-tit1-c").show();	},1000);}  }); if (re2 == "tv55dtt") { $(".popu2-ch25b, .list-updt, .popu2-ch011").show(); const reg1 = $(data).find(".post-body #tv55dtt").data("tvdd");   $(function(){ const url6 = "https://api.themoviedb.org/3/tv/"+reg1+"/credits?api_key=15f53be40c96f3f37966cffc7c22fc4d";
fetch(url6, {credentials: "same-origin",cache: 'force-cache'}).then(function(response) {return response.json();}).then(function(huutv) {const cassy = huutv["cast"];
const gotz = new Object(cassy);const tm1i = gotz.length;  
  $(function(){if (tm1i > 1 ){let tvo="";for (let i = 0; i < tm1i; i++) {const gk1c = JSON.stringify(gotz[i]["profile_path"]);  const gk2c = gk1c.replace(/"/g,"");const po = gk2c.length;  if (po > 5 ) {const gk1 = JSON.stringify(gotz[i]["name"]);  const gk2 = gk1.replace(/"/g,"");const gk1b = JSON.stringify(gotz[i]["character"]);  const gk2b = gk1b.replace(/"/g,"");const cid = JSON.stringify(gotz[i]["id"]);  const cid2 = cid.replace(/"/g,"");
 tvo+="<div class='photo-act2-gg' data-cid='"+cid2+"'><img src='https://image.tmdb.org/t/p/w200" +gk2c + "'/><div class='char-name-gg'>" + gk2b + "</div><div class='pers-name-gg'>" + gk2 + "</div></div>";  } else {const gk1 = JSON.stringify(gotz[i]["name"]);  const gk2 = gk1.replace(/"/g,"");const gk1b = JSON.stringify(gotz[i]["character"]);  const gk2b = gk1b.replace(/"/g,"");const cid = JSON.stringify(gotz[i]["id"]);  const cid2 = cid.replace(/"/g,"");
 tvo+="<div class='photo-act2-gg' data-cid='"+cid2+"'><img src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi_a5tp-irW1lLhr62FPHyyX1ghVRRhFBw69LSEm7mmzKTiGeI6b0-m0w2hCRUX6FEAR0QvPzvzL473jVyMFSGS3DR-Vqdw_YMhILs8qV-8gD5MVlLj_utxWZLMyVnuFdH1BGs3-0rrOnr8jh5YYt8BOJ3GR4nPWa9LwGS96OUBoVwOAz3evOlSEJHy4Lw/s1600-rw-e30/kkkon.webp'/><div class='char-name-gg'>" + gk2b + "</div><div class='pers-name-gg'>" + gk2 + "</div></div>";} }  $(".popu2-ch25").show();$(".popu2-ch2").append(tvo);
 $(function(){  const cassy21 = huutv["crew"];const goc = new Object(cassy21);const goc2 = goc.length;  for (var i = 0; i < goc2; i++) {
const goc5 = JSON.stringify(goc[i]["job"]);const g7 = goc5.replace(/"/g,""); if (g7 == "Executive Producer"){const g9 = JSON.stringify(goc[i]["name"]);const g10 = g9.replace(/"/g,"");const bgo54 = JSON.stringify(goc[i]["id"]);const g11 = $(".cas-len-tt2");g11.show();g11.append("<p class='pep-job' data-cid='"+bgo54+"'>"+g10+"</p>");$(".cas-len-tt").show();} }});    } else { $(".popu2-ch2").append("<div class='non-data32'>まだキャストのデータはありません&#12290;</div>");$(".popu2-ch25").hide();}});
}).catch(function(error) {$(error).hide();});});$(function(){const url6 = "https://api.themoviedb.org/3/tv/"+reg1+"?api_key=15f53be40c96f3f37966cffc7c22fc4d&append_to_response=videos";
fetch(url6, {credentials: "same-origin",cache: 'force-cache'}).then(function(response) {return response.json();}).then(function(huu2) {
  const go = new Object(huu2);  const pa25= JSON.stringify(huu2["videos"]["results"][0]);const pa2 = new Object(pa25);  const nj = huu2["genres"].length;   const nj2 = huu2["videos"]["results"].length;const g1 = JSON.stringify(huu2["genres"][0]["name"]);const tv1 = JSON.stringify(huu2.episode_run_time[0]);  if(tv1 > 5){const bv = $(".dat-po1v");bv.show();bv.find("div").append(tv1);$(".popu2-tit00, .list-updt").show();}
  const tv2 = JSON.stringify(huu2.last_episode_to_air["season_number"]);  if(tv2 > 0){const bv = $(".dat-po2v");bv.show();bv.find("div").append(tv2);}
  const tv3 = JSON.stringify(huu2.number_of_episodes);  if(tv3 > 2){const bv = $(".dat-po2ss");bv.show();bv.find("div").append(tv3);}
  const tv5 = JSON.stringify(huu2["first_air_date"]);const tv55 = tv5.replace(/"/g,"");  if(tv5.length > 5){const bv = $(".dat-po3v3");bv.show();bv.find("div").append(tv55);}
  const tv6 = JSON.stringify(huu2["last_air_date"]);const tv66 = tv6.replace(/"/g,"");  if(tv6.length > 5){const bv = $(".dat-po3v");bv.show();bv.find("div").append(tv66);}
    const tv7 = JSON.stringify(huu2["networks"][0]["name"]);const tv77 = tv7.replace(/"/g,"");  if(tv7.length > 2){const bv = $(".list-sub-up");bv.show();bv.find("div").append(tv77);}
     const tv8 = JSON.stringify(huu2["type"]);const tv88 = tv8.replace(/"/g,"");  if(tv8.indexOf("Mini") >= 0) {const bv = $(".list-sub-up2");bv.show();bv.find("div").append(tv88);}    if(cnt.length  > 1){const bv = $(".coutry-lis55");bv.show();bv.find("div").append(cnt);}
      $(function(){if (nj2 > 0 ){let vidon="";for (let i = 0; i < nj2; i++) {const gk1c = JSON.stringify(huu2["videos"]["results"][i]["key"]);  const gk2c = gk1c.replace(/"/g,"");  vidon+="<div class='yout89z99' id='ovvv2iiz99'><a data-lity='data-lity' href='https://www.youtube.com/watch?v="+gk2c+"' rel='noopener noreferrer' target='_blank' title=''><div class='yout89z-in99'/><img class='youimg599 lazy' src='https://i.ytimg.com/vi/"+gk2c+"/mqdefault.jpg'/></a></div>"; $(".popu2-tit1, .popu2-ch2b1xx").show(); }   $(".popu2-ch2b1").append(vidon); } });  $(function(){if (nj > 0 ){let tvog="";for (let i = 0; i < nj; i++) {  const gk1c5 = JSON.stringify(huu2["genres"][i]["name"]);  const gk2c5 = gk1c5.replace(/"/g,""); tvog+="<div class='gend2'>"+gk2c5+",</div>";  } $(".list-sub-up37").append(tvog);$(".list-sub-up3").show();    }}); $(function(){ const htv1 = JSON.stringify(huu2["homepage"]);const htv2 = htv1.replace(/"/g,"");const bef = htv2.length;   
  if (bef > 3){const bv = $(".popu2-ch2b1-c");bv.prepend("<a href='"+htv2+"' rel='noopener noreferrer' target='_blank'>Homepage <i class='im-external-link-alt'/></a>"); }  });}).catch(function(error) {$(error).hide();});});  } else if (re2 == "mv55dtt"){ $(".popu2-ch25b, .list-updt, .popu2-ch011").show(); const reg2 = $(data).find(".post-body #mv55dtt").data("zonb");
   $(function(){     const url6 = "https://api.themoviedb.org/3/movie/"+reg2+"?api_key=15f53be40c96f3f37966cffc7c22fc4d&append_to_response=credits,videos";
fetch(url6, {credentials: "same-origin",cache: 'force-cache'}).then(function(response) {return response.json();}).then(function(huu2) {
const go = JSON.stringify(huu2); const go2 = new Object(huu2["credits"]["cast"]);  const go5 = JSON.stringify(huu2["credits"]["cast"]);const go25 = new Object(go5); const tk1 = go2.length;   const rob = JSON.stringify(huu2["release_date"]);const rob5 = rob.replace(/"/g,"");$(function(){if (tk1 > 1 ){
let movcc="";for (let i = 0; i < tk1; i++) {const gk1c = JSON.stringify(go2[i]["profile_path"]);  const gk2c = gk1c.replace(/"/g,"");const po = gk2c.length;  if (po > 5 ) {const gk1 = JSON.stringify(go2[i]["name"]);  const gk2 = gk1.replace(/"/g,"");const gk1b = JSON.stringify(go2[i]["character"]);  const gk2b = gk1b.replace(/"/g,"");const cid = JSON.stringify(go2[i]["id"]);  const cid2 = cid.replace(/"/g,"");
movcc+="<div class='photo-act2-gg' data-cid='"+cid2+"'><img src='https://image.tmdb.org/t/p/w200" +gk2c + "'/><div class='char-name-gg'>" + gk2b + "</div><div class='pers-name-gg'>" + gk2 + "</div></div>";
  } else {const gk1 = JSON.stringify(go2[i]["name"]);  const gk2 = gk1.replace(/"/g,"");const gk1b = JSON.stringify(go2[i]["character"]);  const gk2b = gk1b.replace(/"/g,"");const cid = JSON.stringify(go2[i]["id"]);  const cid2 = cid.replace(/"/g,"");
 movcc+="<div class='photo-act2-gg' data-cid='"+cid2+"'><img src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi_a5tp-irW1lLhr62FPHyyX1ghVRRhFBw69LSEm7mmzKTiGeI6b0-m0w2hCRUX6FEAR0QvPzvzL473jVyMFSGS3DR-Vqdw_YMhILs8qV-8gD5MVlLj_utxWZLMyVnuFdH1BGs3-0rrOnr8jh5YYt8BOJ3GR4nPWa9LwGS96OUBoVwOAz3evOlSEJHy4Lw/s1600-rw-e30/kkkon.webp'/><div class='char-name-gg'>" + gk2b + "</div><div class='pers-name-gg'>" + gk2 + "</div></div>";}
} $(".popu2-ch25").show(); $(".popu2-ch2").append(movcc); } else { $(".popu2-ch2").append("<div class='non-data32'>まだキャストのデータはありません&#12290;</div>");$(".popu2-ch25").hide();}});
    const nj5 = huu2["genres"].length;       $(function(){if (nj5 > 0 ){let mgenn="";for (let i = 0; i < nj5; i++) {  const gk1c5 = JSON.stringify(huu2["genres"][i]["name"]);  const gk2c5 = gk1c5.replace(/"/g,"");  mgenn+="<div class='gend2'>"+gk2c5+",</div>";  }$(".list-sub-up37").append(mgenn);  $(".list-sub-up3").show();    }}); 
   if(cnt.length  > 1){const bv = $(".coutry-lis55");bv.show();bv.find("div").append(cnt+"<br/>("+rob5+")");} const nj2 = huu2["videos"]["results"].length;   $(function(){if (nj2 > 0 ){let mvidd="";for (let i = 0; i < nj2; i++) {const gk1c = JSON.stringify(huu2["videos"]["results"][i]["key"]);   const gk2c = gk1c.replace(/"/g,""); 
  mvidd+="<div class='yout89z99' id='ovvv2iiz99'><a data-lity='data-lity' href='https://www.youtube.com/watch?v="+gk2c+"' rel='noopener noreferrer' target='_blank' title=''><div class='yout89z-in99'/><img class='youimg599 lazy' src='https://i.ytimg.com/vi/"+gk2c+"/mqdefault.jpg'/></a></div>";
 $(".popu2-tit1, .popu2-ch2b1xx").show(); }   $(".popu2-ch2b1").append(mvidd); } });  
   $(function(){ const htv1 = JSON.stringify(huu2["homepage"]);const htv2 = htv1.replace(/"/g,"");const bef = htv2.length;   
  if (bef > 2){const bv = $(".popu2-ch2b1-c");bv.prepend("<a href='"+htv2+"' rel='noopener noreferrer' target='_blank'>Homepage <i class='fas fa-external-link-alt'/></a>");}  });
 $(function(){    const tv1 = JSON.stringify(huu2["budget"]);const num5 = Number(tv1).toLocaleString();   if(tv1 > 5){const bv = $(".dat-po2yy");bv.show();bv.find("div").append("$"+num5);$(".popu2-tit00, .list-updt").show();}  const tv2 = JSON.stringify(huu2["revenue"]);const num52 = Number(tv2).toLocaleString();
  if(tv2 > 0){const bv = $(".dat-po2");bv.show();bv.find("div").append("$"+num52);}
        const go2 = new Object(huu2["credits"]["crew"]); const tk1 = go2.length;    for (var i = 0; i < tk1; i++) {const dk1 = JSON.stringify(go2[i]["job"]);const dk3 = dk1.replace(/"/g,""); if (dk3 == "Director"){const dk2 = JSON.stringify(go2[i]["name"]);const dk5 = dk2.replace(/"/g,"");const bgo = JSON.stringify(go2[i]["id"]);const bv = $(".dat-po1-d");bv.show();bv.find("div").append("<p class='pep-job' data-cid='"+bgo+"'>"+dk5+"</p>");$(".popu2-tit00, .list-updt").show();}   
         const dk1b = JSON.stringify(go2[i]["job"]);const dk3b = dk1b.replace(/"/g,""); if (dk3b == "Screenplay"){const dk2b = JSON.stringify(go2[i]["name"]);const dk5b = dk2b.replace(/"/g,"");const bgo = JSON.stringify(go2[i]["id"]);const bv = $(".dat-po3-s");bv.show();bv.find("div").append("<p class='pep-job' data-cid='"+bgo+"'>"+dk5b+"</p>");}} });
  }).catch(function(error) {$(error).hide();});});} else {$(this).hide();}
   $(function(){	setTimeout(function(){	$(".pofuk55").hide(); $(".acten-1dr-nn55, .popu2-ch-net2, .popu2-ch25b, .top-sch-01, .popu2-ch2b1-c, .popu2-ch2b1xx-cc, .acten-on2dr-in, #x-class-bt00").show();	},2000);});    }      }); $(document).ajaxStop(function() { $(".pofuk55").hide(); $(".acten-1dr-nn55, .popu2-ch-net2, .popu2-ch25b, .top-sch-01, .popu2-ch2b1-c, .popu2-ch2b1xx-cc, .acten-on2dr-in, #x-class-bt00").show(); });  });   }
 $(document).on('click', '.sabu777dr, .acten-on1dr, .acten-on1dr-in', function () { const pall =$(".popu2-ch2");pall.scrollLeft(0); $(".sabu777dr, .acten-on1dr, .acten-on2dr").fadeOut(200);$(".top-sch-01 div, .popu2-ch2,  .popu2-ch2b1, .popu2-ch2b1-c, .popu2-ch011-blist li div, .popu2-ch011 li div, .acten-1dr, .popu2-ch2b1xx-cc, .cas-len-tt2, .img-all-rev112, #ts-rev-saw-all,#titelt-cobet1").empty();$("#twit-post0-top-TPX-img2").remove();$(".popu2-ch25, .popu2-ch011 li, .popu2-ch011-blist li, .popu2-tit1, .popu2-ch2b1xx, .popu2-tit00, .list-updt, .popu2-tit1, .top-sch-01, .popu2-ch-net2, .popu2-tit1-c, .popu2-ch2b1-c, .popu2-ch2b1xx-cc, .acten-on2dr-in, .cas-len-tt, .list-sub-aud10, #x-class-bt003, .img-all-rev112,#x-class-bt00").hide();$("#x-class-bt00").addClass("rev-ck-po00");$(".hideonly-tw").removeClass("dspp10");$('body').removeClass('sccansell');  $(".menu-dbb1, #x-class-bt,#ad-bottom-pc0, #ad-bottom-f1ads, .ad-sticky2, #x-class-bt, #x-class-bt003b").fadeIn(200);});
   $(document).on('click', '.huupo65', function () { const bau = $(this).text();window.open(bau, '_blank')    });   
       $(document).on('click', '.photo-act2-gg, .pep-job', function () {const gu = $(this).data('cid');   window.open("https://www.net-frx.com/person?="+gu+"=id", '_blank')     }); });